### ISSUE TITLE
Issue with starting Cagebreak from ~/.bashrc 

### ISSUE THREAD

**Issue by kinleyd** [project-repo/cagebreak#15]
This is a strange one: If I start Cagebreak automatically at login with ~/.bashrc running 'exec cagebreak', no matter what application I try to run, Firefox is run instead.

I also see this message at the time, though I'm not sure if that is related to an earlier execution of the emacs daemon:

Warning: due to a long standing Gtk+ bug
https://gitlab.gnome.org/GNOME/gtk/issues/221
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.

The problem doesn't occur if I log in and start Cagebreak manually.

**Comment by project-repo** [comment]
The first thing that comes to mind is that you added `exec cagebreak` to
the .bashrc instead of the .bash_profile. This means that
`exec cagebreak` is executed every time a shell is opened. If you in
addition have `exec firefox` specified within the cagebreak
configuration, this in particular means that firefox is run every time
you start a shell (and since cagebreak runs `sh` internally to run
commands in particular when you try to open programs using cagebreak).

Does moving `exec cagebreak` to the .bash_profile solve the problem?

I'm no expert on emacs configuration though, so I don't know what that
part is about... Does it still occur? Is there any other information
that may be relevant to this?

cheers
project-repo

**Comment by kinleyd** [comment]
Hmm, I didn't know .bashrc behaved that way. I always thought it was initialized at login and was called again only if one manually sourced it. Yes, having it in .bash_profile resolves the issue. I normally use systemd and slim login but here I'm trying to configure this test system with pure Wayland applications, to the extent it's possible. So I slapped it in .bashrc, as a quick and dirty temporary setting.

Turns out this is the same problem I had mentioned earlier where I had Firefox spawning indefinitely. At that time I hadn't realized that it had occurred after adding 'exec cagebreak' to .bashrc. At the time I had Firefox set to autostart in cagebreak/config, and I had a number of tabs including Gmail set to open automatically. Each tab automatically opened a new instance of Firefox, and so on ... and I had a temporary block on my Gmail account, which was a bit frightening!

Anyway, I'm relieved the solution was a simple one! 

Thank you for getting back.
