### ISSUE TITLE
Spawn an Application in Specified Workspace

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#54]
I want to st autostarting all of my apliciations. The problem is that when an applicaiton starts in the autostart, it only launchs in the first workspace. I am wondering if there is a wayto clauch applciation in another workspace.

**Comment by project-repo** [comment]
Hi VehementHam

This is an issue which is solved by our socket functionality and a bit of scripting. Please reference SECURITY.md and the appropriate man pages for details.

Note: You must know that you have to take care of the views of each process. The issue is that when you run an executable there might be a small delay until a view is opened. If your script changes workspaces etc. in the meantime, the view will pop up there. This is impossible for us to solve once and for all, as executables may open multiple views and we have no way of knowing what the end user would want us to do with them.

cheers
project-repo
