### ISSUE TITLE
Is cagebreak compatible with waybar?

### ISSUE THREAD

**Issue by nipsis** [project-repo/cagebreak#6]
Hello,

I have tried to use waybar with cagebreak and I only get the following error message:

[2021-09-24 21:48:49.220] [error] Failed to acquire required resources.

Is cagebreak compatible with waybar?

**Comment by project-repo** [comment]
Hi,
No, at the moment, cagebreak is not compatible with waybar. The reason
for this is, as much as I can tell, that cagebreak does not support
the layer-shell protocol.
However, seeing as this is quite a commonly used protocol, now that
I've looked into this a bit I think that adding support for this is
probably a good idea. It probably won't make it into the next
release (which should be coming soon) but we'll let you know here once
we make any progress.
Cheers,
project-repo

**Comment by nipsis** [comment]
Fantastic, thank you!

**Comment by project-repo** [comment]
Hi nipsis,
We've been looking into the implementation of the layer-shell protocol
in cagebreak and have decided that atm we will not be implementing it:
The reason is that this would add a huge amount of (potentially buggy)
code to the current code base (probably 500-1000 loc) which isn't really
justified by the gain. Moreover, having task bars, background images,
etc. was never really within the scope of cagebreak which is designed to
have as many features as necessary and be as minimalistic as possible.
Thanks anyways for the report though!
Cheers,
project-repo

**Comment by nipsis** [comment]
No problem! I completely understand. Thank you for looking into this! :)

**Comment by project-repo** [comment]
For future visitors: Cagebreak now supports the layer-shell protocol, so waybar should work for Cagebreak. If not, please open a new issue.
Cheers,
project-repo
