### ISSUE TITLE
Suggestion: Default values if config file not found

### ISSUE THREAD

**Issue by ghost** [project-repo/cagebreak#8]
Apologies for opening two tickets instead of one, but I thought that these two suggestions are different enought they merit their own "issue".

Would replicating the behaviour in ratpoison (if no config file is found, load predefined defaults) something you would be interested in? I personally found confusing when I first tried cagebreak that it wouldn't start without a config file, coming from ratpoison. Of course, other people's experience might be different.

**Comment by project-repo** [comment]
Hi nipsis,
No problem we actually prefer having multiple issues to work with
instead of one single issue with unrelated ideas!

I don't think that we will be hard-coding any configuration directly
into cagebreak since it seems to me that this is something that would
eventually start diverging from, for example, the example configuration
in the repository and would probably sooner or later cause confusion.
An alternative would be to add the installation of a default
configuration to the install target so that when you install cagebreak
a default configuration is written to some system configuration
directory. That way cagebreak could check whether this file is available
and use it as a fallback. What do you think?
Cheers,
project-repo

**Comment by nipsis** [comment]
I think that's a great idea.

Having a default config file installed on /etc/cagebreak/config (like Sway for example) would ensure everybody has a working config file and can copy it to ~/.config/cagebreak if they want to tweak it.

**Comment by project-repo** [comment]
We have just released simple default config for meson install.

Cheers,
project-repo
